#-------------------------------
# General Site Settings
title: Sindhya Balasubramanian

#-------------------------------
# Author Settings
author:
  name: Sindhya Balasubramanian
  image: 01.jpg
  say-hello: Hello, I’m <strong>Sindhya Balasubramanian</strong>
  bio: I am a <strong>data science</strong> enthusiast fascinated by the math that goes into using this data to drive business impact. I am curious, I spent 5 years exploring code respositories and datasets for a livelihood and am currently pursuing my Masters in Data Science from Northeastern University

#-------------------------------
# Contact links
email: balasubramanian.si@northeastern.edu
linkedin: https://www.linkedin.com/in/sindhya-balasubramanian/
github: https://github.com/sindhya1781
