#-------------------------------
# General Site Settings
title: Sindhya Balasubramanian

#-------------------------------
# Author Settings
author:
  name: Sindhya Balasubramanian
  image: 01.jpg
  say-hello: Hello, I’m <strong>Sindhya Balasubramanian</strong>
  bio: I am a <strong>data science enthusiast</strong> fascinated by how data and math can drive business impact. I am a curious individual - I spent 5 years exploring code respositories and datasets for a livelihood and am currently pursuing my Masters in Data Science from Northeastern University. You can read more about my journey in the 'About Me' section


#-------------------------------
# Contact links
email: balasubramanian.si@northeastern.edu
linkedin: https://www.linkedin.com/in/sindhya-balasubramanian/
github: https://github.com/sindhya1781
